apiVersion: v1
kind: Secret
metadata:
  name: minimal-spec
stringData:
  OLLAMA_API_KEY: ""
---
apiVersion: agents.hermeum.app/v1alpha1
kind: HermesAgent
metadata:
  name: minimal-spec
spec:
  hermes:
    image:
      tag: v2026.6.5
    config:
      # apiServer:
      #   enabled: true
      # webhook:
      #   enabled: true
      raw:
        model:
          base_url: https://ollama.com/v1
          default: kimi-k2.6
          provider: ollama-cloud
    workspace:
      dotEnv:
        secretRef:
          name: minimal-spec
